# Site settings
title: Portfolio Pedro Lucas
description: Portfolio de projetos
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pedro Lucas
user_description: Sou desenvolvedor front-end com experiência em HTML, CSS (SASS e LESS) e JavaScript, incluindo TypeScript e frameworks como React. Sigo as melhores práticas de desenvolvimento, como a metodologia BEM e Styled Components, para criar aplicações escaláveis e eficientes. Além disso, utilizo ferramentas como Redux Toolkit para gerenciamento global de estado e otimização de performance.
user_title: Front-End Software Developer
email: pedro.wo13@gmail.com
github_username:  pedroluccs
linkedin_username:  pedroluccs

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
